/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m09.uf1;

public class CryptoUtils {

    public static void AsymmetricEncryption(){

        

    }
}
